### PR TITLE
Added 404 Page

### PR DESCRIPTION
**Pull request by DaneRainbird**
Very important redirect, please consider adding.

### CODE REVIEW

**Comment by SameGD** [comment]
hmmmm, I will file this in my file system for future consideration. please note in the future, I do take bribes to expedite this process.

**Comment by gitchly** [comment]
Do it

**Comment by gitchly** [comment]
I double dog dare you to add that 404 page 🐶🐶

**Comment by SameGD** [comment]
Well if it's a double dog dare, I guess I have no choice.

**Comment by SameGD** [comment]
I trust this solves your problem: https://samegd.github.io/404.html.

**Comment by DaneRainbird** [comment]
Understandable, thank you for this. I will now close this PR.

**Pull request closed without merging**
